Repository ISIS3510-202420-Team23/AndletSwift, pull requests merged in 2024-10, with the labels that each got.

#21 Develop smart feature
  Andlet/Andlet.xcodeproj/project.pbxproj
  Andlet/Andlet/AndletApp.swift
  Andlet/Andlet/Assets.xcassets/Icon.imageset/Andlet A (1).png
  Andlet/Andlet/Assets.xcassets/Icon.imageset/Contents.json
  Andlet/Andlet/ContentView.swift
  Andlet/Andlet/Models/OfferModel.swift
  Andlet/Andlet/Models/PropertyModel.swift
  Andlet/Andlet/ViewModels/Offers/OfferDetailViewModel.swift
  Andlet/Andlet/ViewModels/Offers/OfferRentViewModel.swift
  Andlet/Andlet/ViewModels/Offers/OfferViewModel.swift
  Andlet/Andlet/ViewModels/UserRelated/UserViewsViewModel.swift
  Andlet/Andlet/Views/Helpers/Heading.swift
  Andlet/Andlet/Views/Helpers/OfferImageCarouselView.swift
  Andlet/Andlet/Views/Homepage/HomepageView.swift
  Andlet/Andlet/Views/Offers/OfferDetailView.swift
  Andlet/Andlet/Views/Offers/OfferRentView.swift
  Andlet/Andlet/Views/Offers/OfferView.swift
Labels: bug, view, model

#23 Develop other feature using other sensor - Detecting shake
  Andlet/Andlet.xcodeproj/project.pbxproj
  Andlet/Andlet/ViewModels/Offers/OfferRentViewModel.swift
  Andlet/Andlet/Views/Helpers/Heading.swift
  Andlet/Andlet/Views/Helpers/MainTabView.swift
  Andlet/Andlet/Views/Helpers/ShakeDetector.swift
  Andlet/Andlet/Views/Homepage/HomepageView.swift
  Andlet/Andlet/Views/HomepageRent/HomepageRentView.swift
Labels: view

#25 [Develop smart feature] Fixing clean message and delete filter bar from the landlords homepage
  Andlet/Andlet/Views/Homepage/HomepageView.swift
  Andlet/Andlet/Views/HomepageRent/HomepageRentView.swift
Labels: bug, view

#26 [bugfix] Fix form issue
  Andlet/Andlet.xcodeproj/project.pbxproj
  Andlet/Andlet/Views/Forms/Step1View.swift
  Andlet/Andlet/Views/Forms/Step2View.swift
  Andlet/Andlet/Views/Helpers/Extensions.swift
Labels: bug

#27 [bugfix] Ensuring that only one property and offer is created when pressing save
  Andlet/Andlet/Views/Forms/Step3View.swift
Labels: bug

#28 [bugfix] Fixing fetching offers within a data range in filters
  Andlet/Andlet.xcodeproj/project.pbxproj
  Andlet/Andlet.xcodeproj/xcshareddata/xcschemes/Andlet.xcscheme
  Andlet/Andlet/Analytics/AnalyticsView.swift
  Andlet/Andlet/ViewModels/Filters/FilterViewModel.swift
  Andlet/Andlet/ViewModels/Offers/OfferViewModel.swift
  Andlet/Andlet/Views/Filters/FiltersSearchView.swift
Labels: bug

#29 User functionality
  Andlet/Andlet.xcodeproj/project.pbxproj
  Andlet/Andlet/Models/UserModel.swift
  Andlet/Andlet/ViewModels/AuthenticationViewModel.swift
  Andlet/Andlet/ViewModels/Offers/OfferDetailViewModel.swift
  Andlet/Andlet/ViewModels/Offers/OfferRentViewModel.swift
  Andlet/Andlet/ViewModels/Offers/OfferViewModel.swift
  Andlet/Andlet/Views/Filters/FiltersSearchView.swift
  Andlet/Andlet/Views/Forms/Step1View.swift
  Andlet/Andlet/Views/Forms/Step2View.swift
  Andlet/Andlet/Views/Forms/Step3View.swift
  Andlet/Andlet/Views/Helpers/Heading.swift
  Andlet/Andlet/Views/Helpers/MainTabLandlordView.swift
  Andlet/Andlet/Views/Helpers/MainTabView.swift
  Andlet/Andlet/Views/Homepage/HomepageView.swift
  Andlet/Andlet/Views/HomepageRent/CreateMoreButton.swift
  Andlet/Andlet/Views/Offers/OfferDetailView.swift
  Andlet/Andlet/Views/Profile/ProfileView.swift
  Andlet/Andlet/Views/WelcomeViews/AuthenticationView.swift
  Andlet/Andlet/Views/WelcomeViews/ProfilePickerView.swift
  Andlet/Andlet/Views/WelcomeViews/WelcomeIndividualPageView.swift
  Andlet/Andlet/Views/WelcomeViews/WelcomePageView.swift
Labels: bug, view, model

#31 implement cas andlet swiftapp
  Andlet/Andlet.xcodeproj/project.pbxproj
  Andlet/Andlet/AndletApp.swift
  Andlet/Andlet/Info.plist
  Andlet/Andlet/Models/UserActions.swift
  Andlet/Andlet/Utils/LocationManager.swift
  Andlet/Andlet/ViewModels/Offers/OfferDetailViewModel.swift
  Andlet/Andlet/Views/Helpers/CheckDaysSinceLastContact.swift
  Andlet/Andlet/Views/Helpers/Heading.swift
  Andlet/Andlet/Views/Homepage/HomepageView.swift
  Andlet/Andlet/Views/Offers/OfferDetailView.swift
Labels: enhancement

#33 [bugfix] Photo picker not opening when clicking at a random part of the screen
  Andlet/Andlet.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Andlet/Andlet/Views/Forms/Step3View.swift
  Andlet/Andlet/Views/Helpers/ImagePickerView.swift
Labels: bug

#34 Fetching user info from database and fixing homepage padding
  Andlet/Andlet/AndletApp.swift
  Andlet/Andlet/ViewModels/UserRelated/HeadingViewModel.swift
  Andlet/Andlet/Views/Helpers/Heading.swift
  Andlet/Andlet/Views/Helpers/SearchAndFilterBar.swift
  Andlet/Andlet/Views/Homepage/HomepageView.swift
Labels: bug, view

#38 [loading auth-screen] upload auth logic
  Andlet/Andlet.xcodeproj/project.pbxproj
  Andlet/Andlet/AndletApp.swift
  Andlet/Andlet/Utils/LocationManager.swift
  Andlet/Andlet/Views/Helpers/Heading.swift
  Andlet/Andlet/Views/Profile/ProfileView.swift
  Andlet/Andlet/Views/WelcomeViews/AuthenticationView.swift
Labels: enhancement, view

#39 [bugfix] back navigation
  Andlet/Andlet/Views/WelcomeViews/AuthenticationView.swift
Labels: bug

#41 Modify send email
  Andlet/Andlet/AndletApp.swift
  Andlet/Andlet/Views/Offers/OfferDetailView.swift
Labels: enhancement

#42 [Bug fix] No emojis allowed on fields
  Andlet/Andlet.xcodeproj/project.pbxproj
  Andlet/Andlet/Info.plist
  Andlet/Andlet/Views/Filters/FiltersSearchView.swift
  Andlet/Andlet/Views/Forms/Step1View.swift
  Andlet/Andlet/Views/Forms/Step2View.swift
  Andlet/Andlet/Views/Helpers/IncrementDecrementView.swift
  Andlet/Andlet/Views/Helpers/StringExtensions.swift
Labels: bug

#43 [BugFix] LigthMode always on
  Andlet/Andlet/Info.plist
Labels: bug

#45 [Fix bugs] landlords offer view ready, filters and photos
  Andlet/Andlet.xcodeproj/project.pbxproj
  Andlet/Andlet.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Andlet/Andlet/Cache/ImageCacheManager.swift
  Andlet/Andlet/ViewModels/Offers/OfferViewModel.swift
  Andlet/Andlet/ViewModels/Properties/PropertyViewModel.swift
  Andlet/Andlet/Views/Filters/FiltersSearchView.swift
  Andlet/Andlet/Views/Helpers/OfferImageCarouselView.swift
  Andlet/Andlet/Views/Homepage/HomepageView.swift
  Andlet/Andlet/Views/Offers/OfferRentView.swift
Labels: bugFix

#49 [BugFix] Not Allowing Only Spaces on Text Fields
  Andlet/Andlet/ViewModels/Filters/FilterViewModel.swift
  Andlet/Andlet/ViewModels/Offers/OfferViewModel.swift
  Andlet/Andlet/ViewModels/Properties/PropertyOfferData.swift
  Andlet/Andlet/Views/Filters/FiltersSearchView.swift
  Andlet/Andlet/Views/Forms/Step1View.swift
  Andlet/Andlet/Views/Forms/Step2View.swift
  Andlet/Andlet/Views/Helpers/PriceField.swift
  Andlet/Andlet/Views/Helpers/StringExtensions.swift
  Andlet/Andlet/Views/Homepage/HomepageView.swift
Labels: bugFix

#51 Bug fix timeout log in
  Andlet/Andlet.xcodeproj/project.pbxproj
  Andlet/Andlet/ViewModels/AuthenticationViewModel.swift
  Andlet/Andlet/Views/Helpers/Heading.swift
  Andlet/Andlet/Views/WelcomeViews/AuthenticationView.swift
Labels: bug, bugFix

#52 47 caching feature
  Andlet/Andlet.xcodeproj/project.pbxproj
  Andlet/Andlet/Cache/ImageCacheManager.swift
  Andlet/Andlet/Cache/OfferCacheManager.swift
  Andlet/Andlet/Models/UserModel.swift
  Andlet/Andlet/Utils/NetworkMonitor.swift
  Andlet/Andlet/ViewModels/Offers/OfferDetailViewModel.swift
  Andlet/Andlet/ViewModels/Offers/OfferViewModel.swift
  Andlet/Andlet/ViewModels/Offers/OfferWithProperty.swift
  Andlet/Andlet/Views/Helpers/ShakeDetector.swift
  Andlet/Andlet/Views/Homepage/HomepageView.swift
  Andlet/Andlet/Views/HomepageRent/HomepageRentView.swift
  Andlet/Andlet/Views/Offers/OfferDetailView.swift
  Andlet/Andlet/Views/Offers/OfferRentView.swift
Labels: enhancement

#54 Visible filters] add visible filters
  Andlet/Andlet/Views/Helpers/SearchAndFilterBar.swift
  Andlet/Andlet/Views/Homepage/HomepageView.swift
Labels: enhancement

#56 47 caching feature
  Andlet/Andlet.xcodeproj/project.pbxproj
  Andlet/Andlet/Utils/UserDefaultsExtension.swift
  Andlet/Andlet/ViewModels/Offers/OfferViewModel.swift
  Andlet/Andlet/Views/Homepage/HomepageView.swift
  Andlet/Andlet/Views/Offers/OfferDetailView.swift
Labels: enhancement

#57 [visible-filters] finish visible filters
  Andlet/Andlet.xcodeproj/project.pbxproj
  Andlet/Andlet/Views/Helpers/SearchAndFilterBar.swift
Labels: enhancement

#59 47 caching feature
  Andlet/Andlet.xcodeproj/project.pbxproj
  Andlet/Andlet/Info.plist
  Andlet/Andlet/Utils/UserDefaultsExtension.swift
  Andlet/Andlet/ViewModels/AuthenticationViewModel.swift
  Andlet/Andlet/Views/Helpers/Heading.swift
  Andlet/Andlet/Views/Homepage/HomepageView.swift
  Andlet/Andlet/Views/HomepageRent/HomepageRentView.swift
Labels: enhancement
