Repository ISIS3510-202420-Team23/AndletSwift, pull requests merged in 2024-11, with the labels that each got.

#61 58 implementing local storage for a property
  Andlet/Andlet.xcodeproj/project.pbxproj
  Andlet/Andlet/CoreData.xcdatamodeld/CoreData.xcdatamodel/contents
  Andlet/Andlet/Views/Forms/Step3View.swift
  Andlet/Andlet/Views/Homepage/HomepageView.swift
  Andlet/Andlet/Views/HomepageRent/HomepageRentView.swift
  Andlet/Andlet/Views/Offers/OfferDetailView.swift
Labels: enhancement

#68 58 implementing local storage for a property
  Andlet/Andlet/ViewModels/Properties/PropertyOfferData.swift
  Andlet/Andlet/Views/Forms/Step3View.swift
  Andlet/Andlet/Views/HomepageRent/CreateMoreButton.swift
  Andlet/Andlet/Views/HomepageRent/HomepageRentView.swift
Labels: bug

#72 New peoperty notification
  Andlet/Andlet.xcodeproj/project.pbxproj
  Andlet/Andlet/ViewModels/Properties/PropertyOfferData.swift
  Andlet/Andlet/ViewModels/Properties/PropertyViewModel.swift
  Andlet/Andlet/Views/Forms/Step1View.swift
  Andlet/Andlet/Views/Forms/Step3View.swift
  Andlet/Andlet/Views/Helpers/MainTabLandlordView.swift
  Andlet/Andlet/Views/Homepage/HomepageView.swift
  Andlet/Andlet/Views/HomepageRent/HomepageRentView.swift
  Andlet/Andlet/Views/Offers/OfferDetailView.swift
  Andlet/Andlet/Views/Profile/ProfileView.swift
Labels: bugFix

#73 Fixing profile picture image
  Andlet/Andlet.xcodeproj/project.pbxproj
  Andlet/Andlet/Views/Profile/ProfileView.swift
Labels: bugFix

#80 [Bug-fix] Not allowing New Lines on Form Fields
  Andlet/Andlet/Views/Helpers/StringExtensions.swift
Labels: bugFix

#82 74 create notifications view
  Andlet/Andlet.xcodeproj/project.pbxproj
  Andlet/Andlet/Models/NotificationModel.swift
  Andlet/Andlet/ViewModels/Notifications/NotificationsViewModel.swift
  Andlet/Andlet/Views/Helpers/Extensions.swift
  Andlet/Andlet/Views/Helpers/MainTabLandlordView.swift
  Andlet/Andlet/Views/NotificationsRent/HeaderNotificationsView.swift
  Andlet/Andlet/Views/NotificationsRent/NotificationView.swift
  Andlet/Andlet/Views/NotificationsRent/NotificationsRentView.swift
Labels: enhancement

#84 81 implementing profile and options view
  Andlet/Andlet.xcodeproj/project.pbxproj
  Andlet/Andlet/ViewModels/Bug/BugViewModel.swift
  Andlet/Andlet/Views/Helpers/CustomBugInputField.swift
  Andlet/Andlet/Views/Helpers/StringExtensions.swift
  Andlet/Andlet/Views/Profile/ProfileView.swift
Labels: enhancement
